### ISSUE TITLE
Hackday goals 30/11/2019

### ISSUE THREAD

**Issue by thibaudcolas** [torchbox/django-pattern-library#28]
In GitLab by @helenb on Oct 31, 2019, 08:22

Overall aim: open source the project.

**FE:**
- [x] Check tooling commands
- [x] Update developer documentation if necessary
- [x] Fix accessibility errors reported by axe
- [x] IE11 JS support
- [x] Fix case sensitivity in pattern search

**BE:**
- [x] Check through open issues and see if any of them can be closed
- [ ] Code audit #88
- [x] Check MR #46 and see if this is still needed or if it should be closed
- [ ] Add tests and docs to MR #83 (alphabetise pattern list and remove atomic structure) and merge
- [x] Set up Docker and update developer documentation
- [ ] Tackle context inheritance issues (issue #8)
- [ ] Add pattern variants (nice to have - not essential for open sourcing) #87 

**Either FE or BE:**
- [x] Create github repo - clarify who should own this with Tom D
- [x] Port over code, issues and MR template from gitlab
- [x] Add open source licence
- [x] Check any documentation that needs updating (e.g. repo url)
- [ ] Make sure the authors list in the changelog is up to date #89

**Comment by thibaudcolas** [comment]
In GitLab by @helenb on Nov 30, 2019, 11:27

marked the task **Check MR !16 and see if this is still needed or if it should be closed** as completed

**Comment by thibaudcolas** [comment]
In GitLab by @helenb on Nov 30, 2019, 12:10

marked the task **Set up Docker and update developer documentation** as completed

**Comment by thibaudcolas** [comment]
In GitLab by @helenb on Nov 30, 2019, 12:23

marked the task **Check through open issues and see if any of them can be closed** as completed

**Comment by thibaudcolas** [comment]
In GitLab by @helenb on Nov 30, 2019, 12:23

marked the task **Check tooling commands** as completed

**Comment by thibaudcolas** [comment]
In GitLab by @helenb on Nov 30, 2019, 12:23

marked the task **Update developer documentation if necessary** as completed

**Comment by thibaudcolas** [comment]
In GitLab by @helenb on Nov 30, 2019, 15:48

marked the task **Fix accessibility errors reported by axe** as completed

**Comment by thibaudcolas** [comment]
In GitLab by @helenb on Nov 30, 2019, 15:49

marked the task **IE11 JS support** as completed

**Comment by thibaudcolas** [comment]
In GitLab by @helenb on Nov 30, 2019, 15:49

marked the task **Fix case sensitivity in pattern search** as completed

**Comment by thibaudcolas** [comment]
I’ve updated line items to reflect the open-sourcing work from #50, and extracted remaining line items to their own issues to make it easier to review them. Closing.
